# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  base = "./"
  publish = "./_site/"
  command = "npm run build && npm run build:site"
  [build.environment]
    GIT_LFS_ENABLED = "1"
[[headers]]
  for="/*"
  [headers.values]
    Link = '''
      </css/index.min.css>; rel=preload; as=style, \
      </js/index.min.js>; rel=preload; as=script, \
      </img/icons.svg>; rel=preload; as=image
    '''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000"
    Content-Security-Policy = '''
      default-src 'self';
      base-uri 'self';
      img-src 'self' https://i.imgur.com https://cdn.kernvalley.us https://secure.gravatar.com https://maps.wikimedia.org/osm-intl/ https://via.placeholder.com https://*.githubusercontent.com/;
      script-src 'self' moz-extension: https://cdn.kernvalley.us https://unpkg.com/ https://www.google-analytics.com/ https://www.googletagmanager.com https://polyfill.io/ https://cdn.polyfill.io/ https://www.youtube.com/ https://www.youtube-nocookie.com/;
      style-src 'self' 'unsafe-inline' https://cdn.kernvalley.us https://unpkg.com/ https://fonts.googleapis.com/ https://www.youtube.com/ https://www.youtube-nocookie.com/;
      connect-src 'self' https://cdn.kernvalley.us https://api.kernvalley.us https://api.github.com/ https://unpkg.com/ https://polyfill.io/ https://cdn.polyfill.io/ https://www.google-analytics.com/ https://www.googletagmanager.com/ https://i.imgur.com https://secure.gravatar.com https://maps.wikimedia.org/osm-intl/ https://fonts.gstatic.com/  https://fonts.googleapis.com/ https://via.placeholder.com;
      font-src 'self' https://cdn.kernvalley.us https://fonts.gstatic.com/;
      media-src 'none';
      frame-src https://www.youtube.com https://www.youtube-nocookie.com https://disqus.com;
      object-src: 'none';
      worker-src: 'self';
      manifest-src 'self';
      form-action 'self';
      reflected-xss block;
      block-all-mixed-content;
      upgrade-insecure-requests;
      disown-opener;'''
# [[redirects]]
  # from = ""
  # to = ""
